/***************************************************************************
*
*  $MCD Módulo de definição: GRF  Grafo
*
*  Arquivo gerado:              GRAFO.h
*  Letras identificadoras:      GRF
*
*  Nome da base de software:    
*  Arquivo da base de software: D:\AUTOTEST\PROJETOS\GRAFO.BSW      
*
*  Projeto: 
*  Gestor:  
*  Autores: 
*
*  $HA Histórico de evolução:
*     Versão  Autor    Data     Observações
*     
*
*  $ED Descrição do módulo
*     Implementa um grafo.
*     Múltiplos grafos podem existir simultaneamente.
*     Os grafos possuem uma cabeça que encapsula o seu estado.
*
*
*
***************************************************************************/
